version: '2.0'
# run `docker-compose up` to build, `docker-compose down && docker-compose up` to rebuild
# binaries will be automatically copied to the directory this is run in
services:
  build:
    volumes:
      - .:/host
    image: docker-ethos-ccminer
    container_name: docker-ethos-ccminer
    build:
      context: .
