version: '2.0'
# run `docker-compose up` to build, `docker-compose down && docker-compose up` to rebuild
# binaries will be automatically copied to the directory this is run in
# building more than one of an exe will result in it being overwritten. 
services:
#  bfgminer:
#    volumes:
#      - .:/host
#    image: bfgminer
#    container_name: bfgminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/luke-jr/bfgminer.git
#        MINER_GIT_BRANCH: linux
#        MINER_FOLDER: bfgminer
#        MINER_EXE: bfgminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
  tpruvot-ccminer:
    volumes:
      - .:/host
    image: tpruvot-ccminer
    container_name: tpruvot-ccminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/tpruvot/ccminer.git
        MINER_GIT_BRANCH: linux
        MINER_FOLDER: ccminer
        MINER_EXE: ccminer
        MINER_GEN: ./autogen.sh
        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#  klaust-ccminer:
#    volumes:
#      - .:/host
#    image: klaust-ccminer
#    container_name: klaust-ccminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/KlausT/ccminer.git
#        MINER_GIT_BRANCH: linux
#        MINER_FOLDER: ccminer
#        MINER_EXE: ccminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
  nevermore-ccminer:
    volumes:
      - .:/host
    image: nevermore-ccminer
    container_name: nevermore-ccminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/brian112358/nevermore-miner.git
        MINER_GIT_BRANCH: linux
        MINER_FOLDER: nevermore-miner
        MINER_EXE: ccminer
        MINER_GEN: ./autogen.sh
        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#  zcoin-ccminer:
#    volumes:
#      - .:/host
#    image: zcoin-ccminer
#    container_name: zcoin-ccminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/zcoinofficial/ccminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: ccminer
#        MINER_EXE: ccminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#  cgminer:
#    volumes:
#      - .:/host
#    image: cgminer
#    container_name: cgminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/ckolivas/cgminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: cgminer
#        MINER_EXE: cgminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#  dagger-miner:
#    volumes:
#      - .:/host
#    image: dagger-miner
#    container_name: dagger-miner
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/XDagger/DaggerGpuMiner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: DaggerGpuMiner/GpuMiner
#        MINER_EXE: xdag-gpu
  ethminer:
    volumes:
      - .:/host
    image: ethminer
    container_name: ethminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/ethereum-mining/ethminer.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: ethminer
        MINER_EXE: ethminer/ethminer
        MINER_KERNELS: libethash-cl/kernels/bin/
        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  energiminer:
#    volumes:
#      - .:/host
#    image: energiminer
#    container_name: energipowminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/energicryptocurrency/energiminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: energiminer
#        MINER_EXE: energiminer/energiminer
#        MINER_KERNELS: libnrghash-cl/kernels/bin
#        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
  progpowminer:
    volumes:
      - .:/host
    image: progpowminer
    container_name: progpowminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/ifdefelse/ProgPOW.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: ProgPOW
        MINER_EXE: ethminer/ethminer
        MINER_CONFIG: cmake -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs -DETHASHCL=OFF -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  grin:
#    volumes:
#      - .:/host
#    image: grin
#    container_name: grin
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/mimblewimble/grin.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: grin
#        MINER_EXE: target/release/grin
#        MINER_GEN: cargo build --release
  sgminer:
    volumes:
      - .:/host
    image: sgminer
    container_name: sgminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/tpruvot/sgminer.git
        MINER_GIT_BRANCH: ethash
        MINER_FOLDER: sgminer
        MINER_EXE: sgminer
        MINER_KERNELS: kernel/
        MINER_GEN: ./autogen.sh
        MINER_CONFIG: ./configure
  avermore:
    volumes:
      - .:/host
    image: avermore
    container_name: avermore
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/brian112358/avermore-miner.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: avermore-miner
        MINER_EXE: sgminer
        MINER_GEN: autoreconf -i
        MINER_CONFIG: ./configure
#  silentarmy:
#    volumes:
#      - .:/host
#    image: silentarmy
#    container_name: silentarmy
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/mbevand/silentarmy.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: silentarmy
#        MINER_EXE: silentarmy
#  AMDVerusCoin:
#    volumes:
#      - .:/host
#    image: amdveruscoin
#    container_name: amdveruscoin
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/monkins1010/AMDVerusCoin.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: AMDVerusCoin
#        MINER_EXE: silentarmy sa-solver
  xmr-stak:
    volumes:
      - .:/host
    image: xmr-stak
    container_name: xmr-stak
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/fireice-uk/xmr-stak.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: xmr-stak
        MINER_EXE: bin/xmr-stak bin/libxmrstak_cuda_backend.so bin/libxmrstak_opencl_backend.so
        MINER_CONFIG: cmake -DXMR-STAK_COMPILE=generic -DCPU_ENABLE=ON -DCMAKE_LINK_STATIC=ON -DCUDA_ENABLE=ON -DOpenCL_ENABLE=ON --build .
#  xmrig-amd:
#    volumes:
#      - .:/host
#    image: xmrig-amd
#    container_name: xmrig-amd
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/xmrig/xmrig-amd.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: xmrig-amd
#        MINER_EXE: xmrig-amd
#        MINER_CONFIG: cmake .
#  xmrig-nvidia:
#    volumes:
#      - .:/host
#    image: xmrig-nvidia
#    container_name: xmrig-nvidia
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/xmrig/xmrig-nvidia.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: xmrig-nvidia
#        MINER_EXE: xmrig-nvidia
#        MINER_CONFIG: cmake -DCUDA_ARCH="30;50;60" .
#  xmrig-MoneroOcean:
#    volumes:
#      - .:/host
#    image: xmrig-mo
#    container_name: xmrig-mo
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/MoneroOcean/xmrig.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: xmrig
#        MINER_EXE: xmrig
#        MINER_CONFIG: cmake .
