version: '2.0'
# run `docker-compose up` to build, `docker-compose down && docker-compose up` to rebuild
# binaries will be automatically copied to the directory this is run in
# building more than one of an exe will result in it being overwritten. 
services:
#  beam-cuda:
#    volumes:
#      - .:/host
#    image: beam-cuda
#    container_name: beam-cuda
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/BeamMW/cuda-miner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: cuda-miner
#        CONFIG_CPP: update-alternatives --set gcc /usr/bin/gcc-6
#        MINER_EXE: equihash/beam-cuda-miner
#        MINER_GEN: cmake .
#  beam-amd:
#    volumes:
#      - .:/host
#    image: beam-amd
#    container_name: beam-amd
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/BeamMW/opencl-miner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: opencl-miner
#        CONFIG_CPP: update-alternatives --set gcc /usr/bin/gcc-7
#        MINER_KERNELS: kernels
#        MINER_EXE: beam-opencl-miner
#        MINER_GEN: cmake .
#  bfgminer:
#    volumes:
#      - .:/host
#    image: bfgminer
#    container_name: bfgminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/luke-jr/bfgminer.git
#        MINER_GIT_BRANCH: bfgminer
#        MINER_FOLDER: bfgminer
#        MINER_EXE: bfgminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
  tpruvot-ccminer:
    volumes:
      - .:/host
    image: tpruvot-ccminer
    container_name: tpruvot-ccminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/tpruvot/ccminer.git
        MINER_GIT_BRANCH: linux
        MINER_FOLDER: ccminer
        MINER_EXE: ccminer
        MINER_GEN: ./autogen.sh
        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
        extracuda_cflags: -O3 -lineno -Xcompiler -Wall  -D_FORCE_INLINES
        extracxxflags: -O3 -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16
#  klaust-ccminer:
#    volumes:
#      - .:/host
#    image: klaust-ccminer
#    container_name: klaust-ccminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/KlausT/ccminer.git
#        MINER_GIT_BRANCH: linux
#        MINER_FOLDER: ccminer
#        MINER_EXE: ccminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#        extracuda_cflags: -O3 -lineno -Xcompiler -Wall  -D_FORCE_INLINES
#        extracxxflags: -O3 -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16
  nevermore-ccminer:
    volumes:
      - .:/host
    image: nevermore-ccminer
    container_name: nevermore-ccminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/brian112358/nevermore-miner.git
        MINER_GIT_BRANCH: linux
        MINER_FOLDER: nevermore-miner
        MINER_EXE: ccminer
        MINER_GEN: ./autogen.sh
        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
        extracuda_cflags: -O3 -lineno -Xcompiler -Wall  -D_FORCE_INLINES
        extracxxflags: -O3 -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16
#  suprminer:
#    volumes:
#      - .:/host
#    image: suprminer
#    container_name: suprminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/ocminer/suprminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: suprminer
#        MINER_EXE: ccminer
#        CONFIG_CPP: git clone https://github.com/peters/curl-for-windows.git compat/curl-for-windows
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#        extracuda_cflags: -O3 -lineno -Xcompiler -Wall  -D_FORCE_INLINES
#        extracxxflags: -O3 -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16
#  zcoin-ccminer:
#    volumes:
#      - .:/host
#    image: zcoin-ccminer
#    container_name: zcoin-ccminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/zcoinofficial/ccminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: ccminer
#        MINER_EXE: ccminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#        extracuda_cflags: -O3 -lineno -Xcompiler -Wall  -D_FORCE_INLINES
#        extracxxflags: -O3 -D_REENTRANT -falign-functions=16 -falign-jumps=16 -falign-labels=16
#  cgminer:
#    volumes:
#      - .:/host
#    image: cgminer
#    container_name: cgminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/ckolivas/cgminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: cgminer
#        MINER_EXE: cgminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
#  cuballoon:
#    volumes:
#      - .:/host
#    image: cuballoon
#    container_name: cuballoon
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/Belgarion/cuballoon.git
#        MINER_FOLDER: cuballoon
#        MINER_GIT_BRANCH: master
#        MINER_EXE: cpuminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-crypto --with-curl
#        extracflags: -O2 -Ofast -flto -fuse-linker-plugin -ftree-loop-if-convert-stores -DUSE_ASM -pg
#  dagger-miner:
#    volumes:
#      - .:/host
#    image: dagger-miner
#    container_name: dagger-miner
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/XDagger/DaggerGpuMiner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: DaggerGpuMiner/GpuMiner
#        MINER_EXE: xdag-gpu
  ethminer:
    volumes:
      - .:/host
    image: ethminer
    container_name: ethminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/ethereum-mining/ethminer.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: ethminer
        MINER_EXE: ethminer/ethminer
        MINER_KERNELS: libethash-cl/kernels/bin/
        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  andrea-ethminer:
#    volumes:
#      - .:/host
#    image: andrea-ethminer
#    container_name: andrea-ethminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/AndreaLanfranchi/ethminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: ethminer
#        MINER_EXE: ethminer/ethminer
#        MINER_KERNELS: libethash-cl/kernels/bin/
#        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  ethersocialnetwork-ethminer:
#    volumes:
#      - .:/host
#    image: ethersocialnetwork-ethminer
#    container_name: ethersocialnetwork-ethminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/EthersocialNetwork/ethminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: ethminer
#        MINER_EXE: ethminer/ethminer
#        MINER_KERNELS: libethash-cl/kernels/bin/
#        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  energiminer:
#    volumes:
#      - .:/host
#    image: energiminer
#    container_name: energipowminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/energicryptocurrency/energiminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: energiminer
#        MINER_EXE: energiminer/energiminer
#        MINER_KERNELS: libnrghash-cl/kernels/bin
#        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#        extracxxflags: -std=c++0x
#        CONFIG_CPP: update-alternatives --set gcc /usr/bin/gcc-6
#  progminer:
#    volumes:
#      - .:/host
#    image: progminer
#    container_name: progminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/gangnamtestnet/progminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: progminer
#        MINER_EXE: progminer/progminer
#        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
  progpowminer:
    volumes:
      - .:/host
    image: progpowminer
    container_name: progpowminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/ifdefelse/ProgPOW.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: ProgPOW
        MINER_EXE: ethminer/ethminer
        MINER_CONFIG: cmake -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs -DETHASHCL=OFF -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  ubiqminer:
#    volumes:
#      - .:/host
#    image: ubiqminer
#    container_name: ubiqminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/ubiq/ubqminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: ubqminer
#        MINER_EXE: ethminer/ethminer
#        MINER_KERNELS: libethash-cl/kernels/bin/
#        MINER_CONFIG: cmake -DETHASHCL=ON -DETHASHCUDA=ON -DETHSTRATUM=ON --build .
#  grin:
#    volumes:
#      - .:/host
#    image: grin
#    container_name: grin
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/mimblewimble/grin.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: grin
#        MINER_EXE: /lib/x86_64-linux-gnu/libncursesw.so.5 /lib/x86_64-linux-gnu/libtinfo.so.5 target/release/grin
#  grin-miner:
#    volumes:
#      - .:/host
#    image: grin-miner
#    container_name: grin-miner
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/mimblewimble/grin-miner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: grin-miner
#        MINER_EXE: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libncursesw.so.5 /lib/x86_64-linux-gnu/libtinfo.so.5 target/release/grin-miner grin-miner.toml
#        MINER_KERNELS: target/release/plugins
#  nheqminer-amd:
#    volumes:
#      - .:/host
#    image: nheqminer-amd
#    container_name: nheqminer-amd
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/nicehash/nheqminer.git
#        MINER_GIT_BRANCH: Linux
#        MINER_FOLDER: nheqminer/Linux_cmake/nheqminer_AMD
#        MINER_EXE: nheqminer_AMD
#        MINER_CONFIG: cmake . -DOPENCL_LIBRARY=/usr/lib/x86_64-linux-gnu/libOpenCL.so -DOPENCL_INCLUDE_DIRECTORY=/opt/AMDAPPSDK-3.0/include
#  nheqminer-cuda:
#    volumes:
#      - .:/host
#    image: nheqminer-cuda
#    container_name: nheqminer-cuda
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/nicehash/nheqminer.git
#        MINER_GIT_BRANCH: Linux
#        MINER_FOLDER: nheqminer/Linux_cmake/nheqminer_cuda_tromp
#        MINER_EXE: nheqminer_cuda_tromp
#        MINER_GEN: cd ../../cpu_xenoncat/Linux/asm/ ; ./assemble.sh
#        MINER_CONFIG: cmake .
#  nheqminer-veruscoin-amd:
#    volumes:
#      - .:/host
#    image: nheqminer-veruscoin-amd
#    container_name: nheqminer-veruscoin-amd
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/veruscoin/nheqminer.git
#        MINER_GIT_BRANCH: Linux
#        MINER_FOLDER: nheqminer/Linux_cmake/nheqminer_AMD
#        MINER_EXE: nheqminer_AMD
#        MINER_CONFIG: cmake . -DOPENCL_LIBRARY=/usr/lib/x86_64-linux-gnu/libOpenCL.so -DOPENCL_INCLUDE_DIRECTORY=/opt/AMDAPPSDK-3.0/include
#  nheqminer-veruscoin-cuda:
#    volumes:
#      - .:/host
#    image: nheqminer-veruscoin-cuda
#    container_name: nheqminer-veruscoin-cuda
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/veruscoin/nheqminer.git
#        MINER_GIT_BRANCH: Linux
#        MINER_FOLDER: nheqminer/Linux_cmake/nheqminer_cuda_tromp
#        MINER_EXE: nheqminer_cuda_tromp
#        MINER_GEN: cd ../../cpu_xenoncat/Linux/asm/ ; ./assemble.sh
#        MINER_CONFIG: cmake .
#  nheqminer-bitcoin-gold:
#    volumes:
#      - .:/host
#    image: nheqminer-bitcoin-gold
#    container_name: nheqminer-bitcoin-gold
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/martin-key/nheqminer-bitcoin-gold.git
#        MINER_GIT_BRANCH: kost
#        MINER_FOLDER: nheqminer-bitcoin-gold/nheqminer
#        MINER_EXE: nheqminer
#        MINER_CONFIG: cmake -DXENON=1 -DMARCH=-m64 .
#  nodecore-pow-cuda-miner:
#    volumes:
#      - .:/host
#    image: nodecore-pow-cuda-miner
#    container_name: nodecore-pow-cuda-miner
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/VeriBlock/nodecore-pow-cuda-miner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: nodecore-pow-cuda-miner
#        MINER_EXE: nodecore_pow_cuda
#        MINER_GEN: /usr/local/cuda/bin/nvcc -gencode=arch=compute_50,code="sm_50,compute_50" -gencode=arch=compute_52,code="sm_52,compute_52" -gencode=arch=compute_61,code="sm_61,compute_61" -gencode=arch=compute_70,code="sm_70,compute_70" -I/usr/local/cuda/include -I. -O3 -Xcompiler -Wall  -D_FORCE_INLINES --ptxas-options=-v --maxrregcount=64 -o nodecore_pow_cuda kernel.cu main.cpp Miner.cpp -Xcompiler -static-libgcc -Xcompiler -static-libstdc++ -std=c++11
#  nodecore-pow-AMD-cuda-miner:
#    volumes:
#      - .:/host
#    image: nodecore-pow-AMD-cuda-miner
#    container_name: nodecore-pow-AMD-cuda-miner
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/monkins1010/nodecore-pow-AMD-cuda-miner.git
#        MINER_GIT_BRANCH: AMDVERSION
#        MINER_FOLDER: nodecore-pow-AMD-cuda-miner
#        MINER_EXE: nodecore_pow_cuda veri_amd
#        MINER_GEN: /usr/local/cuda/bin/nvcc -gencode=arch=compute_50,code="sm_50,compute_50" -gencode=arch=compute_52,code="sm_52,compute_52" -gencode=arch=compute_61,code="sm_61,compute_61" -gencode=arch=compute_70,code="sm_70,compute_70" -I/usr/local/cuda/include -I. -O3 -Xcompiler -Wall -D_FORCE_INLINES --ptxas-options=-v --maxrregcount=64 -o nodecore_pow_cuda kernel.cu -std=c++11
#  nsgminer:
#    volumes:
#      - .:/host
#    image: nsgminer
#    container_name: nsgminer
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/ghostlander/nsgminer.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: nsgminer
#        MINER_EXE: nsgminer
#        MINER_GEN: ./autogen.sh
#        MINER_CONFIG: ./configure --with-cuda=/usr/local/cuda
  sgminer:
    volumes:
      - .:/host
    image: sgminer
    container_name: sgminer
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/tpruvot/sgminer.git
        MINER_GIT_BRANCH: ethash
        MINER_FOLDER: sgminer
        MINER_EXE: sgminer
        MINER_KERNELS: kernel/
        MINER_GEN: ./autogen.sh
        MINER_CONFIG: ./configure
        extracflags: -g -O2
  avermore:
    volumes:
      - .:/host
    image: avermore
    container_name: avermore
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/brian112358/avermore-miner.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: avermore-miner
        MINER_EXE: sgminer
        MINER_GEN: autoreconf -i
        MINER_CONFIG: ./configure
#  fancyix:
#    volumes:
#      - .:/host
#    image: fancyix
#    container_name: fancyix
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/fancyIX/sgminer-phi2-branch.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: sgminer-phi2-branch
#        MINER_EXE: sgminer
#        MINER_KERNELS: kernel
#        MINER_GEN: autoreconf -i
#        MINER_CONFIG: ./configure
#  silentarmy:
#    volumes:
#      - .:/host
#    image: silentarmy
#    container_name: silentarmy
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/mbevand/silentarmy.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: silentarmy
#        MINER_EXE: silentarmy sa-solver
#  AMDVerusCoin:
#    volumes:
#      - .:/host
#    image: amdveruscoin
#    container_name: amdveruscoin
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/monkins1010/AMDVerusCoin.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: AMDVerusCoin
#        MINER_EXE: silentarmy sa-solver
  xmr-stak:
    volumes:
      - .:/host
    image: xmr-stak
    container_name: xmr-stak
    build:
      context: .
      args:
        MINER_GIT_URL: https://github.com/fireice-uk/xmr-stak.git
        MINER_GIT_BRANCH: master
        MINER_FOLDER: xmr-stak
        MINER_EXE: bin/xmr-stak bin/libxmrstak_cuda_backend.so bin/libxmrstak_opencl_backend.so
        MINER_CONFIG: cmake -DXMR-STAK_COMPILE=generic -DCPU_ENABLE=ON -DCMAKE_LINK_STATIC=ON -DCUDA_ENABLE=ON -DOpenCL_ENABLE=ON --build .
#  xcash-all:
#    volumes:
#      - .:/host
#    image: xcash-all
#    container_name: xcash-all
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/X-CASH-official/XCASH_ALL_Miner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: XCASH_ALL_Miner
#        MINER_EXE: bin/xmr-stak bin/libxmrstak_cuda_backend.so bin/libxmrstak_opencl_backend.so
#        MINER_CONFIG: cmake -DXMR-STAK_COMPILE=generic -DCPU_ENABLE=ON -DCMAKE_LINK_STATIC=ON -DCUDA_ENABLE=ON -DOpenCL_ENABLE=ON --build .
#  xmr-aeon-stak:
#    volumes:
#      - .:/host
#    image: xmr-aeon-stak
#    container_name: xmr-aeon-stak
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/IndeedMiners/xmr-aeon-stak.git
#        MINER_GIT_BRANCH: dev
#        MINER_FOLDER: xmr-aeon-stak
#        MINER_EXE: bin/xmr-stak bin/libxmrstak_cuda_backend.so bin/libxmrstak_opencl_backend.so
#        MINER_CONFIG: cmake -DXMR-STAK_COMPILE=generic -DCPU_ENABLE=ON -DCMAKE_LINK_STATIC=ON -DCUDA_ENABLE=ON -DOpenCL_ENABLE=ON --build .
#  xmrig-amd:
#    volumes:
#      - .:/host
#    image: xmrig-amd
#    container_name: xmrig-amd
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/xmrig/xmrig-amd.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: xmrig-amd
#        MINER_EXE: xmrig-amd
#        MINER_CONFIG: cmake .
#  xcash-amd:
#    volumes:
#      - .:/host
#    image: xcash-amd
#    container_name: xcash-amd
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/X-CASH-official/XCASH_AMD_Miner.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: XCASH_AMD_Miner
#        MINER_EXE: XCASH_AMD_Miner
#        MINER_CONFIG: cmake .
#  xmrig-nvidia:
#    volumes:
#      - .:/host
#    image: xmrig-nvidia
#    container_name: xmrig-nvidia
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/xmrig/xmrig-nvidia.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: xmrig-nvidia
#        MINER_EXE: xmrig-nvidia
#        MINER_CONFIG: cmake -DBUILD_SHARED_LIBS=OFF -DITK_DYNAMIC_LOADING=OFF -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs -DCUDA_ARCH=30;50;60 .
#  xmrig-MoneroOcean:
#    volumes:
#      - .:/host
#    image: xmrig-mo
#    container_name: xmrig-mo
#    build:
#      context: .
#      args:
#        MINER_GIT_URL: https://github.com/MoneroOcean/xmrig.git
#        MINER_GIT_BRANCH: master
#        MINER_FOLDER: xmrig
#        MINER_EXE: xmrig
#        MINER_CONFIG: cmake .
